---
title: "FWS Eagle Wind Mortality Model"
author: "Michael Evans, Defenders of Wildlife"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
runtime: shiny
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(DT)
library(flexdashboard)
library(ggplot2)
library(plotly)
library(shiny)
library(viridis)

load("data/app_data.RData")
source("helper_fxns.R")
source("exposure.R")
source("fatality.R")

```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r selector, echo = FALSE}
selectInput("sites", 
            "Choose a Site", 
            choices = c("", levels(Bay16$SITE)), 
            selected = NULL)
```


```{r update, echo = FALSE}
actionButton("update", "Update Distributions")
```


```{r calculate, echo = FALSE}
actionButton("calculate", "Calculate Fatalities")

```

The [U.S. Fish and Wildlife Service](https://www.fws.gov/endangered/laws-policies/)
uses a Bayesian model to estimate the number of eagles likely to be killed by proposed wind projects.
This approach combines prior information about eagle collision rates and exposure across existing wind farms, with observed estimates of eagle activity at proposed sites to estimate the likely number of fatalities.

This dashboard allows you to explore how prior interact with survey data to produce predicted eagle fatalities.

`r hr()`

```{r note, echo = FALSE}
helpText("Note: To ensure this app loads quickly, we use data collected on 
17 Dec 2016 rather than real-time  scraping of the Fish and Wildlife Service's 
website. We will update the data on a regular basis.")
```

Column {data-width=400}
-----------------------------------------------------------------------

### Prior Distribution of Collision Rates

```{r collisions, echo = FALSE}
renderPlotly({
  plot_ly()%>%
  add_trace(x = ~collision$x, y = ~collision$y, type = "scatter", mode = "lines",
            fill = "tozeroy", name = "Prior", line = list(color = vir_col(1)),
            text = ~paste("Prior probability of Collision Rate = ",
                          round(collision$x, 3),
                          "<br> is ",
                          round(collision$y/collision$n, 3),
                          sep = ""),
            hoverinfo = "text")%>%
      layout(#title = "Prior Collision Rates",
             xaxis = list(title = "Collision Rate (per Exposure)"),
             yaxis = list(title = "Probability"))
})

```

### Exposure

```{r exposures, echo = FALSE}

exposure(input, output, session)
plotlyOutput("exposure")
```

> Observed exposure is the value measured at a site during pre-construction surveys.


Column {data-width=600}
-----------------------------------------------------------------------

### Data Table

```{r datatable, echo = FALSE}
cur_dat <- reactive({
  if(input$sites == ""){Bay16}
  else{
    Bay16[Bay16$SITE == input$sites, ]
    }
})

DT::renderDataTable({
  minitab <- select(cur_dat(), 
                    SITE, TURBINES, 
                    EFFORT, FLIGHT_MIN, COLLISIONS)
  DT::datatable(minitab,
                options = list(
                  rownames = FALSE,
                  pageLength = 12,
                  lengthMenu = c(10, 12, 15, 20))
                )
})
```

> Data taken from Appendix S1 in  [Bay et al. (2016). The Journal of Wildlife Management 80(6): 1000-1010](http://onlinelibrary.wiley.com/doi/10.1002/jwmg.21086/full).

### Fatalities

```{r fatalities, echo = FALSE}

fatality(input, output, session)
plotlyOutput("fatal")
```
